---
total_semantic_labels: 73
dynamic_labels: [8, 58]
invalid_labels: []
object_labels:
  - 3
  - 5
  - 6
  # - 7
  - 9
  - 10
  - 11
  - 12
  # - 13
  - 14
  - 15
  - 16
  - 18
  - 19
  - 20
  - 21
  # - 22
  # - 23
  - 24
  - 25
 # - 26
  - 27
  - 28
  - 29
  - 31
  - 32
  - 33
  - 34
  #- 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  #- 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
surface_places_labels:
  - 2
  - 30
  - 45
label_names:
  - {label: 0, name: wall, name_descriptive: a wall}
  - {label: 1, name: building, name_descriptive: a part of a building}
  - {label: 2, name: floor, name_descriptive: a floor}
  - {label: 3, name: tree, name_descriptive: a tree}
  - {label: 4, name: ceiling, name_descriptive: a ceiling}
  - {label: 5, name: bed, name_descriptive: a bed}
  - {label: 6, name: windowpane, name_descriptive: a windowpane}
  - {label: 7, name: cabinet, name_descriptive: a cabinet}
  - {label: 8, name: person, name_descriptive: a person}
  - {label: 9, name: door, name_descriptive: a door}
  - {label: 10, name: plant, name_descriptive: plant life}
  - {label: 11, name: curtain, name_descriptive: a curtain}
  - {label: 12, name: chair, name_descriptive: a chair}
  - {label: 13, name: car, name_descriptive: a car}
  - {label: 14, name: water, name_descriptive: water}
  - {label: 15, name: painting, name_descriptive: a painting}
  - {label: 16, name: sofa, name_descriptive: a sofa}
  - {label: 17, name: house, name_descriptive: a house}
  - {label: 18, name: mirror, name_descriptive: a mirror}
  - {label: 19, name: fence, name_descriptive: a fence}
  - {label: 20, name: desk, name_descriptive: a desk}
  - {label: 21, name: rock, name_descriptive: a rock}
  - {label: 22, name: wardrobe, name_descriptive: a wardrobe}
  - {label: 23, name: lamp, name_descriptive: a lamp}
  - {label: 24, name: bathtub, name_descriptive: a bathtub}
  - {label: 25, name: base, name_descriptive: a base}
  - {label: 26, name: box, name_descriptive: a box}
  - {label: 27, name: sink, name_descriptive: a sink}
  - {label: 28, name: fireplace, name_descriptive: a fireplace}
  - {label: 29, name: refrigerator, name_descriptive: a refrigerator}
  - {label: 30, name: stairs, name_descriptive: stairs}
  - {label: 31, name: case, name_descriptive: a case}
  - {label: 32, name: pillow, name_descriptive: a pillow}
  - {label: 33, name: toilet, name_descriptive: a toilet}
  - {label: 34, name: book, name_descriptive: a book}
  - {label: 35, name: bench, name_descriptive: a bench}
  - {label: 36, name: stove, name_descriptive: a stove}
  - {label: 37, name: computer, name_descriptive: a computer}
  - {label: 38, name: towel, name_descriptive: a towel}
  - {label: 39, name: light, name_descriptive: a light}
  - {label: 40, name: chandelier, name_descriptive: a chandelier}
  - {label: 41, name: streetlight, name_descriptive: a streetlight}
  - {label: 42, name: booth, name_descriptive: a booth}
  - {label: 43, name: television receiver, name_descriptive: a television receiver}
  - {label: 44, name: pole, name_descriptive: a pole}
  - {label: 45, name: escalator, name_descriptive: an escalator}
  - {label: 46, name: ottoman, name_descriptive: an ottoman}
  - {label: 47, name: bottle, name_descriptive: a bottle}
  - {label: 48, name: poster, name_descriptive: a poster}
  - {label: 49, name: stool, name_descriptive: a stool}
  - {label: 50, name: barrel, name_descriptive: a barrel}
  - {label: 51, name: basket, name_descriptive: a basket}
  - {label: 52, name: bag, name_descriptive: a bag}
  - {label: 53, name: oven, name_descriptive: an oven}
  - {label: 54, name: ball, name_descriptive: a ball}
  - {label: 55, name: food, name_descriptive: food}
  - {label: 56, name: microwave, name_descriptive: a microwave}
  - {label: 57, name: pot, name_descriptive: a pot}
  - {label: 58, name: animal, name_descriptive: an animal}
  - {label: 59, name: dishwasher, name_descriptive: a dishwasher}
  - {label: 60, name: screen, name_descriptive: a projection screen}
  - {label: 61, name: trashcan, name_descriptive: a trashcan}
  - {label: 62, name: fan, name_descriptive: a fan}
  - {label: 63, name: plate, name_descriptive: plate}
  - {label: 64, name: monitor, name_descriptive: a monitoring device}
  - {label: 65, name: shower, name_descriptive: shower}
  - {label: 66, name: radiator, name_descriptive: radiator}
  - {label: 67, name: glass, name_descriptive: a drinking glass}
  - {label: 68, name: clock, name_descriptive: a clock}
  - {label: 69, name: flag, name_descriptive: a flag}
  - {label: 70, name: blanket, name_descriptive: a blanket}
  - {label: 71, name: backpack, name_descriptive: a backpack}
  - {label: 72, name: drone, name_descriptive: a drone}
