---
search:
  type: CosSimSearch
  room:
    normalize_similarities: false
    use_softmax: false
    use_mean: false
  object:
    normalize_similarities: false
    use_softmax: false
    use_mean: false
verbose: true
room_prob_threshold: 0.15
object_prob_threshold: 0.65
enable_one_by_one_navigation: true
always_publish_waypoints: true
min_object_vertices: 20
